name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: First Job
      - run:
          echo "ğŸ‰ The job was Manually triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          Check out repository code
          actions/checkout@v3
          echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
          echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
          List files in the repository
          |
            ls ${{ github.workspace }}
          echo "ğŸ This job's status is ${{ job.status }}."
      - name: Second Job
      - run:
          echo "ğŸ‰ The job was Manually triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          Check out repository code
          actions/checkout@v3
          echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
          echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
          List files in the repository
          |
            ls ${{ github.workspace }}
          echo "ğŸ This job's status is ${{ job.status }}."
  
